/* ============================================================
   WINGZ HUT — MENU DATA
   ------------------------------------------------------------
   To change a price, just edit the number.
   To rename an item, edit its "name" or "desc".
   Items can have a single "price" OR a "variants" array
   (e.g. Regular / Large).
   ============================================================ */

const SHOP = {
  name: "Wingz Hut",
  tagline: "Wings · Burgers · Kebab · Grill",
  phone: "020 8981 2455",
  phoneDial: "+442089812455",
  address: "29 Burdett Road, Mile End, London E3 4TT",
  hours: "Open 7 days · 11am – 11pm",
  web: "www.wingzhut.co.uk",
};

const MENU = [
  {
    id: "wings",
    title: "Wings Meal",
    icon: "drumstick",
    image: "assets/img/wings.jpg",
    note: "All served with fries & drink",
    items: [
      { no: "1",  name: "5 Hot Wings",   desc: "with fries & drink", price: 5.99 },
      { no: "2",  name: "5 Naga Wings",  desc: "with fries & drink", price: 6.79 },
      { no: "3",  name: "5 Grill Wings", desc: "with fries & drink", price: 6.79 },
      { no: "3A", name: "5 BBQ Wings",   desc: "with fries & drink", price: 6.79 },
      { no: "4",  name: "5 Sticky Wings", desc: "with fries & drink", price: 6.79 },
      { no: "5",  name: "5 Saucy Wings", desc: "with fries & drink", price: 6.79 },
    ],
  },
  {
    id: "fried-chicken",
    title: "Fried Chicken Meal",
    icon: "drumstick",
    image: "assets/img/fried_chicken.jpg",
    items: [
      { no: "6",   name: "2 Pcs Chicken", desc: "with fries", price: 5.60 },
      { no: "7",   name: "2 Pcs Chicken & 2 Wings", desc: "with fries & drink", price: 7.50 },
      { no: "8",   name: "1 Pc Chicken, 3 Hot Wings", desc: "with fries & drink", price: 7.00 },
      { no: "9",   name: "3 Pcs Chicken, 3 Hot Wings", desc: "with fries", price: 9.00 },
      { no: "10",  name: "6 Chicken Nuggets", desc: "with fries & drink", price: 6.50 },
      { no: "10A", name: "Chicken Popcorn", desc: "with fries & drink", price: 6.50 },
    ],
  },
  {
    id: "burgers",
    title: "Burger Meal",
    icon: "sandwich",
    image: "assets/img/burger_cheese.jpg",
    items: [
      { no: "11",  name: "Chicken Fillet Burger", desc: "with fries", price: 6.00 },
      { no: "11A", name: "Chicken Burger with Cheese", desc: "fries & drink", price: 7.30 },
      { no: "12",  name: "Chicken Fillet Burger, 2 Wings", desc: "with fries & drink", price: 7.40 },
      { no: "13",  name: "Chicken Fillet Burger, 1 Pc Chicken & 2 Wings", desc: "with fries & drink", price: 8.40 },
      { no: "14",  name: "Spicy Chicken Burger", desc: "with fries & drink", price: 7.00 },
      { no: "14A", name: "Spicy Chicken Burger, 2 Wings", desc: "with fries & drink", price: 8.00 },
      { no: "14B", name: "Naga Chicken Burger", desc: "with fries & drink", price: 7.50 },
      { no: "14C", name: "Cheesy Chicken Burger", desc: "with fries & drink", price: 7.50 },
      { no: "15",  name: "Veggie / Fish / Spicy Bean Burger", desc: "with fries & drink", price: 6.30 },
      { no: "15A", name: "Veggie / Fish / Spicy Bean Tower Burger", desc: "with fries & drink", price: 7.20 },
      { no: "16",  name: "Chicken or Lamb Tower Burger", desc: "fried onions & cheese, fries & drink", price: 7.50 },
      { no: "17",  name: "Mini Beef or Cheese Burger", desc: "with fries & drink", price: 5.50 },
      { no: "18",  name: "Mini Cheese Burger & 3 Wings", desc: "with fries & drink", price: 7.00 },
      { no: "19",  name: "Double Beef or Cheese Burger", desc: "with fries & drink", price: 6.50 },
      { no: "20",  name: "½ Pounder Burger", desc: "with fries & drink", price: 7.50 },
      { no: "21",  name: "¼ Pounder Burger", desc: "with fries", price: 6.00 },
      { no: "22",  name: "¼ Pounder Burger, 2 Wings", desc: "with fries & drink", price: 7.40 },
      { no: "23",  name: "Smash Burger", desc: "with fries & drink", price: 10.00 },
      { no: "23A", name: "Mega Burger", desc: "with fries & drink", price: 8.00 },
      { no: "24",  name: "Gourmet Burger", desc: "with fries & drink", price: 8.20 },
    ],
  },
  {
    id: "grill-burger",
    title: "Grill Burger",
    icon: "flame",
    image: "assets/img/burger_gourmet.jpg",
    items: [
      { no: "25", name: "Grill Chicken or Spicy Grill Burger", desc: "with fries & drink", price: 7.40 },
      { no: "26", name: "Chicken Grill Burger & 2 Grill Wings", desc: "with fries & drink", price: 8.50 },
      { no: "27", name: "Double Grill Chicken Burger", desc: "with fries & drink", price: 8.20 },
    ],
  },
  {
    id: "wraps",
    title: "Wraps",
    icon: "croissant",
    image: "assets/img/wrap.jpg",
    items: [
      { no: "29", name: "Grill Chicken Wrap", desc: "with fries & drink", price: 7.80 },
      { no: "30", name: "Chicken or Lamb Sheek Kebab Wrap", desc: "with fries & drink", price: 6.80 },
      { no: "31", name: "Chicken or Lamb Wrap", desc: "with fries & drink", price: 7.20 },
      { no: "32", name: "Chicken Shawarma Wrap", desc: "with fries & drink", price: 7.50 },
    ],
  },
  {
    id: "doner",
    title: "Doner Meal",
    icon: "beef",
    image: "assets/img/doner.jpg",
    note: "Please mention pitta, nan or fries when ordering",
    items: [
      { no: "37",  name: "Meat & Chips", desc: "", price: 7.00 },
      { no: "37A", name: "Doner Meat Only (Regular)", desc: "", price: 8.00 },
      { no: "38",  name: "Doner Meat & Chips", desc: "", price: 8.30 },
      { no: "39",  name: "Lamb Doner Meal", desc: "with pitta / nan / fries & drink", variants: [ { label: "Regular", price: 8.40 }, { label: "Large", price: 9.00 } ] },
      { no: "40",  name: "Chicken Doner Meal", desc: "with pitta / nan / fries & drink", variants: [ { label: "Regular", price: 8.40 }, { label: "Large", price: 9.00 } ] },
      { no: "41",  name: "Chicken or Lamb Satkora Doner", desc: "with pitta / nan / fries & drink", variants: [ { label: "Regular", price: 8.80 }, { label: "Large", price: 9.30 } ] },
      { no: "42",  name: "Naga Chicken or Lamb Doner Meal", desc: "with pitta / nan / fries & drink", price: 8.80 },
      { no: "43",  name: "Mix Doner", desc: "with pitta / nan / fries & drink", price: 9.00 },
      { no: "44",  name: "Lamb Doner Roll & 2 Wings", desc: "with fries & drink", price: 7.50 },
      { no: "45",  name: "Chicken Burger with Doner", desc: "with fries & drink", price: 9.00 },
      { no: "45A", name: "Straight Cut or Garlic Doner", desc: "with pitta / nan / fries & drink", price: 8.50 },
    ],
  },
  {
    id: "grill-chicken",
    title: "Grill Chicken",
    icon: "drumstick",
    image: "assets/img/chicken_grill.jpg",
    items: [
      { no: "46", name: "¼ Grill Chicken", desc: "with 2 grill wings, fries & drink", price: 8.00 },
      { no: "47", name: "½ Grill Chicken", desc: "with nan or fries & drink", price: 9.30 },
      { no: "48", name: "Whole Grill Chicken", desc: "with salad", price: 15.50 },
      { no: "49", name: "Whole Grill Chicken", desc: "with salad, 2 fries & 1.5L drink", price: 20.00 },
    ],
  },
  {
    id: "sides",
    title: "Sides & Salad",
    icon: "salad",
    image: "assets/img/platter.jpg",
    items: [
      { no: "28",  name: "Grill Chicken Salad", desc: "with drink", price: 7.50 },
      { no: "28A", name: "Salad Box", desc: "", price: 3.20 },
      { no: "33",  name: "Mozzarella Sticks (5 Pcs)", desc: "with fries & drink", price: 7.00 },
      { no: "34",  name: "Chilli Pepper & Cheese Nuggets (5 Pcs)", desc: "with fries & drink", price: 7.00 },
      { no: "35",  name: "Cheese & Fries", desc: "", price: 6.20 },
    ],
  },
  {
    id: "fish",
    title: "Fish & Chips",
    icon: "fish",
    image: "assets/img/fish.jpg",
    items: [
      { no: "36", name: "Fish & Chips", desc: "with drink", price: 7.40 },
    ],
  },
  {
    id: "family",
    title: "Family Meals",
    icon: "users",
    image: "assets/img/platter.jpg",
    note: "Please mention pitta, nan or fries when ordering",
    items: [
      { no: "50",  name: "Family Platter", desc: "8 pcs chicken, 15 hot wings, 4 reg. fries, 1.5L drink", price: 33.00 },
      { no: "51",  name: "Family Bucket", desc: "2 reg. lamb doner (pitta/nan/fries), 5 pcs chicken, 12 hot wings, 4 reg. fries & 1.5L drink", price: 35.00 },
      { no: "52",  name: "Burger Bucket", desc: "2 beef burger, 2 chicken steak burger, 2 cheese burgers, 2 pcs chicken, 6 wings & 1.5L drink", price: 25.00 },
      { no: "52A", name: "Mega Burger Bucket", desc: "2 beef, 2 chicken steak, 2 cheese, 2 chicken burger, 10 wings, 4 fries & 1.5L drink", price: 29.50 },
      { no: "53",  name: "Mix Bucket", desc: "1 lamb doner (fries/nan/pitta), 8 wings, 5 pcs chicken, 2 reg. fries & 1.5L drink", price: 26.00 },
      { no: "54",  name: "Mix Bucket", desc: "1 beef burger, 1 chicken steak burger, 1 cheese burger, 16 pcs wings, 2 fries & 2 can drinks", price: 20.00 },
    ],
  },
  {
    id: "kids",
    title: "Kids Offer",
    icon: "baby",
    image: "assets/img/fried_chicken.jpg",
    note: "Mention special prep choices in your order",
    items: [
      { no: "", name: "3 Wings & Fries", desc: "", price: 4.20 },
      { no: "", name: "1 Pc Chicken & Fries", desc: "", price: 3.50 },
      { no: "", name: "3 Nuggets & Fries", desc: "", price: 4.20 },
      { no: "", name: "Cheese Burger & Fries", desc: "", price: 4.50 },
      { no: "", name: "Beef Burger & Fries", desc: "", price: 4.50 },
    ],
  },
  {
    id: "wings-offer",
    title: "Wings Offer",
    icon: "star",
    image: "assets/img/wings.jpg",
    items: [
      { no: "", name: "1 Fried Wing", desc: "", price: 0.90 },
      { no: "", name: "6 Naga Wings", desc: "", price: 6.50 },
      { no: "", name: "10 Naga Wings", desc: "with reg. fries", price: 11.00 },
      { no: "", name: "20 Naga Wings", desc: "with 2 reg. fries", price: 20.00 },
      { no: "", name: "10 Grill Wings", desc: "with 1 reg. fries", price: 11.00 },
      { no: "", name: "20 Grill Wings", desc: "with 2 reg. fries", price: 20.00 },
      { no: "", name: "6 Grill Wings Only", desc: "", price: 6.50 },
      { no: "", name: "8 Fried Wings Only", desc: "", price: 7.50 },
      { no: "", name: "13 Fried Wings", desc: "with 1 reg. fries", price: 12.20 },
      { no: "", name: "20 Fried Wings", desc: "with 2 reg. fries", price: 18.50 },
      { no: "", name: "35 Fried Wings", desc: "with 3 reg. fries", price: 31.00 },
    ],
  },
  {
    id: "extras",
    title: "Add Extras",
    icon: "plus",
    image: "assets/img/burger_cheese.jpg",
    items: [
      { no: "", name: "Single Smash Burger", desc: "", price: 8.00 },
      { no: "", name: "Single Chicken Burger", desc: "", price: 5.00 },
      { no: "", name: "Single ¼ Pounder", desc: "", price: 5.00 },
      { no: "", name: "Single Cheese or Beef Burger", desc: "", price: 2.99 },
      { no: "", name: "Single ½ Pounder", desc: "", price: 6.50 },
      { no: "", name: "Single Spicy Chicken Burger", desc: "", price: 5.50 },
      { no: "", name: "Single Fish Burger", desc: "", price: 4.50 },
      { no: "", name: "Single Veggie Burger", desc: "", price: 4.50 },
      { no: "", name: "Single Grill Burger", desc: "", price: 5.40 },
      { no: "", name: "10 Nuggets & 1 Regular Fries", desc: "", price: 8.50 },
      { no: "", name: "1 Hashbrown", desc: "", price: 1.00 },
      { no: "", name: "1 Pitta Bread", desc: "", price: 0.70 },
      { no: "", name: "1 Nan Bread", desc: "", price: 1.50 },
      { no: "", name: "1 Regular Fries", desc: "", price: 2.50 },
      { no: "", name: "1 Large Fries", desc: "", price: 3.50 },
    ],
  },
  {
    id: "drinks",
    title: "Drinks",
    icon: "cup-soda",
    items: [
      { no: "", name: "Pepsi", desc: "1.5L bottle", price: 3.00 },
      { no: "", name: "Coke", desc: "1.5L bottle", price: 3.80 },
      { no: "", name: "Barr Cola", desc: "2L bottle", price: 2.50 },
      { no: "", name: "Can Drink", desc: "Pepsi, Diet Pepsi, Fanta, 7UP, Mirinda, Tango, Capri Sun, Barr Cola, Water", price: 1.50 },
    ],
  },
  {
    id: "sauces",
    title: "Sauces & Dips",
    icon: "droplet",
    items: [
      { no: "", name: "Single Dip Pot", desc: "Mayo, Garlic Mayo, Ketchup, Burger, Chilli, Sweet Chilli or BBQ", price: 0.50 },
      { no: "", name: "1 Ltr Bottle — Garlic Mayonnaise", desc: "", price: 15.00 },
      { no: "", name: "1 Ltr Bottle — Sweet Chilli", desc: "", price: 12.00 },
      { no: "", name: "1 Ltr Bottle — Chilli", desc: "", price: 12.00 },
      { no: "", name: "1 Ltr Bottle — BBQ", desc: "", price: 10.00 },
      { no: "", name: "1 Ltr Bottle — Burger Sauce", desc: "", price: 10.00 },
      { no: "", name: "1 Ltr Bottle — Ketchup", desc: "", price: 8.00 },
    ],
  },
];
